title:            MAESTRO4U
tagline:          A beautiful theme.
description:      삶의 진솔한 모습과 내가 가진 열정을 보여주는 흰도화지
canonical:        http://www.maestro4u.kr

# Owner/author information
owner:
  name:           Hoon Kim
  avatar:         avatar.png
  bio:            "Civil Engineer"
  email:          huni.kim@gmail.com
  twitter:        HuniKim
  github:         maestro4u
  instagram:      
  dribbble:       
  disqus:          
  location:       "Seoul, Korea"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/maestro4u/maestro4u.github.io
    external: true
  - title: Hoon Who?
    url: http://backtothemac2.tistory.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    South Korea
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
